### ISSUE TITLE
Mining Instructions

### ISSUE THREAD

**Issue by Mentors4EDU** [HiveProject2021/Hivecoin#1]
Hi, there isn't any solo mining instructions (without GUI and without Pool), I just want to make sure this is easy to solo-mine directly from a CLI interface, but can't find any documentation to do so.

**Comment by tweetyf** [comment]
Hi, you can use cli to "solo-mine" with CPU, to do so:
1. start hived daemon `hived --daemon`
2. use `hive-cli setgenerate true 4` to generate block, 4 means runing with 4 thread.
3. `hive-cli help` can get you more information.

However due to the network difficulty, its too hard to generate new block, the recommend way to mining solo is build a private mining pool and use third-part mining software
[https://github.com/HiveProject2021/kawpow-pool](https://github.com/HiveProject2021/kawpow-pool)
